org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.overridePathCheck=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=37
sleepdown.miuixSourcePath=C\:/Users/26291/.cache/tb-build/sleepdown/miuix-reference
kotlin.compiler.execution.strategy=in-process
